name: Render and Publish RMarkdown

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'  # Specify your R version

    - name: Install dependencies
      run: |
        sudo apt install -y pandoc
        Rscript -e 'install.packages(c("ggplot2", "knitr", "tidyr", "dplyr", "DT", "scales", "plotly", "maps", "UpSetR", "ggalluvial", "stringr", "grid", "rmarkdown"), repos="https://cloud.r-project.org/")'

    - name: Render RMarkdown
      run: |
        Rscript -e 'rmarkdown::render("report-final.Rmd", output_format = "html_document")'
